algoritmo "Exercício 40"
// Função : 40) Crie um aplicativo que mostre na tela a seguinte contagem:
//                              0 3 6 9 12 15 18 Acabou!
// Autor : Amanda
// Data : 02/08/2021
// Seção de Declarações 
var

contador: Inteiro

inicio

contador <- 0

Enquanto (contador <= 18) faca
         escreva(contador)
         contador <- contador + 3
FimEnquanto
escreva(" Acabou!")


fimalgoritmo
