algoritmo "Exercício 38"
// Função : 38) Escreva um programa que mostre na tela a seguinte contagem:
//                                       6 7 8 9 10 11 Acabou!
// Autor : Amanda
// Data : 02/08/2021
// Seção de Declarações 
var

contador : inteiro

inicio

contador <- 6

Enquanto (contador <=11) faca
         escreva(contador)
         contador <- contador + 1
FimEnquanto
escreva(" Acabou!")
fimalgoritmo
