Algoritmo "Exercício 65"
// Descrição: Desenvolva um programa usando a estrutura “para” que mostre
//            na tela a seguinte contagem:
//            100 90 80 70 60 50 40 30 20 10 0 Acabou!
// Autor(a): Amanda
// Data atual: 23/08/2021
Var

   numero: Inteiro


Inicio

   Para numero de 100 ate 0 passo -10 faca
      escreva(numero)
   FimPara
   escreva(" Acabou!")


Fimalgoritmo