algoritmo "Exercício 20"
// Função : Desenvolva um programa que leia um número inteiro e
//          mostre se ele é PAR ou ÍMPAR.
// Autor : Amanda
// Data : 31/07/2021
// Seção de Declarações
var

numero: Inteiro

inicio

escreval(" ==== PASSO 02 - CONDIÇÕES BÁSICAS ==== ")
escreva("Digite um número: ")
leia(numero)

Se(numero%2=0) entao
    escreva("O número que você digitou é Par")
Senao
     escreva("O número que você digitou é Ímpar")
fimse

fimalgoritmo
