algoritmo "Exercício 39"
// Função : 39) Faça um algoritmo que mostre na tela a seguinte contagem:
//                                10 9 8 7 6 5 4 3 Acabou!
// Autor : Amanda
// Data : 02/08/2021
// Seção de Declarações 
var
contador: inteiro
inicio

contador <- 10

Enquanto (contador >= 3) faca
         escreva(contador)
         contador <- contador - 1
FimEnquanto
           escreva(" Acabou!")


fimalgoritmo
