algoritmo "Exercício 41"
// Função : Desenvolva um programa que mostre na tela a seguinte contagem:
//                                100 95 90 85 80 ... 0 Acabou!
// Autor : Amanda
// Data : 02/08/2021
// Seção de Declarações 
var

contador: Inteiro

inicio

contador <- 100

Enquanto (contador >= 0)  faca
         escreva(contador)
         contador <- contador - 5
FimEnquanto
escreva(" Acabou!")

fimalgoritmo
